// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using ModelData;
using System;

namespace ModelData.Migrations
{
    [DbContext(typeof(RetroCollectNewContext))]
    [Migration("20180828112256_newMigration")]
    partial class newMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ModelData.ClientListModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("GameId");

                    b.Property<string>("UserId")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("ClientListModel");
                });

            modelBuilder.Entity("ModelData.GameListModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Developer")
                        .IsRequired()
                        .HasMaxLength(70);

                    b.Property<string>("Format")
                        .HasMaxLength(70);

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(70);

                    b.Property<string>("Name")
                        .HasMaxLength(70);

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(70);

                    b.Property<string>("ReleaseDateEU")
                        .HasMaxLength(70);

                    b.Property<string>("ReleaseDateJP")
                        .HasMaxLength(70);

                    b.Property<string>("ReleaseDateNA")
                        .HasMaxLength(70);

                    b.HasKey("Id");

                    b.ToTable("GameListModel");
                });
#pragma warning restore 612, 618
        }
    }
}
