// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using ModelData;
using System;

namespace ModelData.Migrations
{
    [DbContext(typeof(RetroCollectNewContext))]
    [Migration("20190618102145_ClientModelRefactor")]
    partial class ClientModelRefactor
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ModelData.ClientListModel", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("GameId")
                        .HasMaxLength(50);

                    b.Property<string>("UserId")
                        .HasMaxLength(50);

                    b.HasKey("ClientId");

                    b.ToTable("ClientListModel");
                });

            modelBuilder.Entity("ModelData.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ClientId");

                    b.HasKey("GameId");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("Game");
                });

            modelBuilder.Entity("ModelData.GameFormat", b =>
                {
                    b.Property<int>("GameFomatId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("GameId");

                    b.Property<string>("IgdbKey");

                    b.HasKey("GameFomatId");

                    b.HasIndex("GameId");

                    b.ToTable("GameFormat");
                });

            modelBuilder.Entity("ModelData.Game", b =>
                {
                    b.HasOne("ModelData.ClientListModel")
                        .WithOne("Game")
                        .HasForeignKey("ModelData.Game", "ClientId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ModelData.GameFormat", b =>
                {
                    b.HasOne("ModelData.Game")
                        .WithMany("FormatId")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
